### PR TITLE
Rebase to 3.34.0

### PR DESCRIPTION
**Pull request by andrunko**
Here are the details on the changes/patches:
- https://github.com/endlessm/gnome-settings-daemon/commit/6624e491 Updated Danish translation
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/9d8935df Update Croatian translation
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/47e25e0d Update Croatian translation
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/6c5866c4 Update Esperanto translation
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/dbf66894 Updated Danish translation
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/09fdbb5b Updated Danish translation
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/4d3fa851 power,media-keys: Signal connector rather than output ID for OSD
  - Dropped: upstream in https://github.com/endlessm/gnome-settings-daemon/commit/ded2c4c35c28422a360e681a455a26895ab99d23
- https://github.com/endlessm/gnome-settings-daemon/commit/5bd33c81 Fix MPRIS issues with disconnecting clients
  - Dropped: upstream in https://github.com/endlessm/gnome-settings-daemon/commit/162379ed515a7af7601207b664b7003c4ca6fe02
- https://github.com/endlessm/gnome-settings-daemon/commit/a101e96b color: Allow night light to be always on
  - Dropped: upstream in https://github.com/endlessm/gnome-settings-daemon/commit/02295dee94bebcdd246c40ccf0120eb2ab714416
- https://github.com/endlessm/gnome-settings-daemon/commit/89f678ab color: Add test for always on and shortened smearing time
  - Dropped: upstream in https://github.com/endlessm/gnome-settings-daemon/commit/0339e6c9a741c713f5881373e5beb8b96ee27438
- https://github.com/endlessm/gnome-settings-daemon/commit/7d410759 Control breathing LED on EC-100 and EC-200
  - Refreshed
- https://github.com/endlessm/gnome-settings-daemon/commit/d75a4fcd power: Disable the auto-logout notification in demo mode
  - Refreshed
- https://github.com/endlessm/gnome-settings-daemon/commit/76752ed3 housekeeping: connect to dconf out of space notifications
  - Kept
- https://github.com/endlessm/gnome-settings-daemon/commit/4ca7bb45 xsettings: Update signature of org.gnome.Mutter.DisplayConfig.GetCurrentState
  - Kept
- https://github.com/endlessm/gnome-settings-daemon/commit/669c38fc keyboard: don't always add an US layout
  - Refreshed
- https://github.com/endlessm/gnome-settings-daemon/commit/2e61ab82 media-keys: Ignore touchpad-toggle if lid is closed
  - Refreshed
- https://github.com/endlessm/gnome-settings-daemon/commit/b83ee2ac Increase blank delay for screensaver
  - Dropped: upstream in https://github.com/endlessm/gnome-settings-daemon/commit/bd840e2a608b69e17dc4ee13ed98e10a7dc5fa99
- https://github.com/endlessm/gnome-settings-daemon/commit/6a5f66e1 power: Do not compute percentage on keyboard disappearing
  - Refreshed
- https://github.com/endlessm/gnome-settings-daemon/commit/2d0dcb8c media-keys: Add mapping for screen brightness cycle key
  - Dropped: upstream in https://github.com/endlessm/gnome-settings-daemon/commit/dce8028ef85c487d2ae39831432104864aa95664
- https://github.com/endlessm/gnome-settings-daemon/commit/757484b7 power: Implement screen brightness cycle up action
  - Dropped: upstream in https://github.com/endlessm/gnome-settings-daemon/commit/61aa8b8c54148a1d8ae93cabe2c6a9923ce74d68
- https://github.com/endlessm/gnome-settings-daemon/commit/dffd532a led-breathe: only build on platforms where the header is available
  - Kept
- https://github.com/endlessm/gnome-settings-daemon/commit/9e1120ff Add translation support for several new languages
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/7f79505e Add Transifex translation infrastructure
  - Kept
- https://github.com/endlessm/gnome-settings-daemon/commit/25c29de0 Commit .pot file
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/0620f681 Latest translations from Transifex
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/70145478 Merged with downstream translations in Transifex
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/2bae53ad Re-apply intentional downstream translations
  - Dropped: translation
- https://github.com/endlessm/gnome-settings-daemon/commit/1fac3277 power: lock screen in handle_suspend_actions
  - Kept
- https://github.com/endlessm/gnome-settings-daemon/commit/1c902ca9 Updates from Transifex
  - Dropped: translation

Debian packaging at https://github.com/endlessm/gnome-settings-daemon/pull/59.

Also depends on https://github.com/endlessm/eos-theme/pull/324.

I also noticed a few daemons got removed in this version with the justification that they are now handled by `mutter`/`gnome-shell`. Those are `gsd-mouse|clipboard|locate-pointer`. From NEWS:
```
Mouse:
- Removed daemon, everything is now implemented in mutter

Mouse:
- Remove locate-pointer, in favor of gnome-shell handling
- Remove mousetweaks support, in favor of gnome-shell handling

Clipboard:
- Removed daemon, everything is now implemented in mutter
```

Talking to @GeorgesStavracas he said we should integrate this all together, so please don't merge just yet, only review for now.

The tags `Version_*` are not pushed also, will push when merging.

https://phabricator.endlessm.com/T27676

### CODE REVIEW

**Comment by andrunko** [comment]
The failures are due to merge conflicts but the branch will be force pushed to master once approved.

**Comment by GeorgesStavracas** [comment]
> dffd532 led-breathe: only build on platforms where the header is available
>   Kept

It can be merged with 7d41075 `Control breathing LED on EC-100 and EC-200`

Otherwise, looks good

**Comment by andrunko** [comment]
> > [dffd532](https://github.com/endlessm/gnome-settings-daemon/commit/dffd532ad693e1e87ca754461cf962e2ef64185e) led-breathe: only build on platforms where the header is available
> > Kept
> 
> It can be merged with [7d41075](https://github.com/endlessm/gnome-settings-daemon/commit/7d4107599c840ab418e8415e72943c8f81e908fc) `Control breathing LED on EC-100 and EC-200`
> 
> Otherwise, looks good

Thanks for the review, this is done now, PR updated.

**Comment by andrunko** [comment]
bot, retest this please

**Comment by andrunko** [comment]
Pushed the tags and now CI is happy :).

**Pull request merged**
