### PR TITLE
Upgrade to 3.34.0-1 from Debian Experimental

### PR DESCRIPTION
**Pull request by andrunko**
Endless-specific changes are rebased on top of upstream version [1].

[1] https://salsa.debian.org/gnome-team/gnome-settings-daemon/merge_requests/6

https://phabricator.endlessm.com/T27676

### CODE REVIEW

**Comment by andrunko** [comment]
Rebased changes after upstream review.

**Comment by GeorgesStavracas** [comment]
Please split the commit that imports the Debian files, from the downstream commits. I know it's not what was done in the past, but I think splitting commits will make our future rebases easier.

**Comment by andrunko** [comment]
> Please split the commit that imports the Debian files, from the downstream commits. I know it's not what was done in the past, but I think splitting commits will make our future rebases easier.

Done, PR updated.

**Comment by andrunko** [comment]
bot, retest this please

**Comment by andrunko** [comment]
Pushed the tags and now CI is happy :).

**Pull request merged**
